- .travis.yml
- pycqed/init/LaFPGA.py
- pycqed/instrument_drivers/meta_instrument/qubit_objects/CBox_driven_transmon.py
- pycqed/instrument_drivers/meta_instrument/qubit_objects/Tektronix_driven_transmon.py
- pycqed/instrument_drivers/physical_instruments/_controlbox/Assembler.py
- pycqed/measurement/pulse_sequences/single_qubit_tek_seq_elts.py
- pycqed/measurement/waveform_control_CC/qasm_to_asm_converter.py
- pycqed/measurement/waveform_control_CC/single_qubit_qasm_seqs.py
- pycqed/test.py
- pycqed/tests/test_qasm_compiler.py
Closes #35 
* Includes all standard single qubit sequences (listed in #35 ) 
* Includes tests for all single qubit qasm sequences, the test tests if the sequences compile 
* Includes basic structure for the "operation_dict" 
What this Pull Request (PR) does not solve: 
* It does not take care of the problem of ensuring all pulses are loaded to the lookuptable
* As it deals with single qubit sequences only it does a direct translation of operations to instructions, it does not take care of the timing step in the compilation (as required for multi-qubit sequences) 
Noting that it does not include the timing step it is set up in such a way that the qasm_to_asm function can be replaced by any arbitrary compiler ( @gtaifu this is where we could plug in an EWI compiler or an adapter to such a …
> Implemented all standard single qubit sequences in QASM

- pycqed/measurement/waveform_control_CC/multi_qubit_qasm_seqs.py
- pycqed/tests/test_qasm_compiler.py
Added functions to write QASM files for two qubit sequences.
Resolves #175.
Includes standard tests for the added functions.
> Two qubit sequences

- pycqed/analysis/fitting_models.py
The recent changes that improved the Rabi analysis seems to have introduced a new bug. It can happen that the frequency is chosen to be negative, leading to an error in the estimation of the phase. 
This is of no consequence when only considering a single curve but leads to problems when calculating the phase difference between two oscillations (as is the case in CZ tuning). 
@lciorciaro @NielsBultink @fluthi could one of you take a look at the one line I changed? I'm asking you guys as you were involved in this change.
> Fix for bug with negative frequencies in fit

- pycqed/analysis/measurement_analysis.py
tomography.py imports measurement_anlaysis.py, which imports Tomo_Multiplexed from tomography. Since Tomo_Multiplexed is not used anywhere it can be safely removed to resolve the circular dependency.
> Removed circular dependency in meas. analysis

- pycqed/measurement/waveform_control_CC/instruction_lib.py
This small addition causes an error to be raised when creating a QWG instruction, if the codeword is out of range for the number of channels used.
> Error message for QWG codewords

- pycqed/measurement/detector_functions.py
Until now, when using an Instrument in msmt_kw of a Function_Detector, an error was raised because Instruments do have a get() function like parameters, but it has a different call signature and is indeed not what the Function_Detector should call.
This small change fixes this issue
> Hotfix for Function_Detector enabling use of Instrument in msmt_kw

- pycqed/analysis/measurement_analysis.py
When we didn't get a peak in the data, the analysis would crash giving the error 'input contains nan values', due to bad fitting.  When setting kappa_guess to 1 instead of 0 (which is the minimum value in the fitting procedure), we prevent the whole procedure from crashing.
> Fixes failing spectroscopy analysis when no peaks are found

- pycqed/analysis/tools/plotting.py
Fixes #271.
- replace 'u' with 'mu' in the unit conversion. This affects the set_xlabel and set_ylabel functions and the instrument monitor.
> Use mu instead of u as SI prefix

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/UHFQuantumController.py
Fixes #275 
- Change the rotation matrix weights to correctly scale UHFQC output when using double sideband demodulation
@AdriaanRol
> fix: DSB demodulation scaling with UHFLI

- pycqed/analysis/fitting_models.py
For the conversion between voltage and flux in the dac-arc, the
physically meaningful constant of 'voltage per phi0' should be used; i.e. how many volts must be applied to get a flux of phi0. This is implemented here in a backwards-compatible way.
> Replaced dac_flux_coefficient by V_per_phi0

- .travis.yml
- requirements.txt
Annoying emails for everyone! 
This change makes travis send you an email when you are the one that makes a commit that breaks a test build. I also added PyGSTi as a dependency so that it can be safely used in any import statements (or potentially in future tests).
> Email update when you break the test builds

- pycqed/measurement/waveform_control/pulsar.py
Fix AWG sequence programming order.
There was no issue (on github, that is).
Comment:
commit #6cba2ca0 randomized the order in which
sequences are uploaded to the AWG by
putting them in a dict and then pulling them out again,
breaking the way in which most of Pycqed uses the 5014.
> hotfix programming order in pulsar

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/UHFQuantumController.py
- pycqed/measurement/detector_functions.py
The channels where put in an array by looping over dict.keys(), which was not guaranteed to preserve ordering. By sorting the keys we guarantee the ordering is the same as the order in which the acquisition channels were defined.
> Fix ordering of channels in UHFQC detector function

- pycqed/analysis/measurement_analysis.py
- pycqed/measurement/awg_sweep_functions_multi_qubit.py
- pycqed/measurement/pulse_sequences/multi_qubit_tek_seq_elts.py
This is part 1 of splitting up pull request #330 
- improve the structure of SSRO analysis
- improve info on SSRO analysis plots
- add option to do an additional preselection pulse before state preparation to remove thermal population
- add generic n-qubit on-off awg sweep function.
There is still room for improvement in SSRO analysis I think (in terms of structure and speed), these are the changes I made to make it usable for us.
Example plot generated by SSRO analysis:
@AdriaanRol
> SSRO_analysis and n-qubit on-off

- pycqed/analysis/measurement_analysis.py
Fixes a bug in Qubit_Spectroscopy_Analysis where the units for the xlabel were not extracted
correctly from self.sweep_unit.
Fixes #386.
In the DCL master version, in measurement_analysis.py:
* line 4927: x_unit=self.sweep_unit ---> x_unit=self.sweep_unit[0]
* line 4957: unit=self.sweep_unit ---> unit=self.sweep_unit[0]
Since this unit was incorrectly retrieved, the set_xlabel function did not receive the correct units, and the x-axis was in Hz instead of GHz.
@AdriaanRol
> Fixes bug in Qubit_Spectroscopy_Analysis where

- pycqed/measurement/measurement_control.py
Fixes a bug in the liveplotting where in heatmaps the y-axis was wrongly displaying the unit twice and not displaying the label/parameter name.
> Fixed ylabels for 2D plotting in MC

- pycqed/analysis/measurement_analysis.py
Changed exponent at which scientific notation kicks in. 
See figures below for example of use. 
Here the scientific exponent does not add anything and IMO only makes it less easy to read in one glance. 
Here it is easily readable. 
IMO numbers up to thousands are easily readable (e.g., 4096 vs 4e3). Above that scientific notation could be useful. 
@antsr @Vintrix I'm asking you to review as you have introduced the change. I guess I should have paid more attention when reviewing.
> Changed powerlimits from -2, 2 to -4, 4

- pycqed/measurement/demonstrator_helper/execute_helpers_CCL.py
- pycqed/measurement/demonstrator_helper/execute_helpers_Starmon.py
@AdriaanRol I needed to change the execute helpers interface to support having tqisa/tasm and also add a qasm file url argument because the Spin side needs the qasm file to differentiate between the qubit measurements. I don't expect it to break the system.
> Enhancement/#410/execute helpers arg change (correct base)

- pycqed/measurement/demonstrator_helper/simulation_helpers.py
Fixes issue #413 by just adding the parameter_name and unit for the qx simulator in the simulation_helper file.
> Fixes the x-axis for QX simulator in Quantum Infinity

- pycqed/measurement/demonstrator_helper/execute_helpers_CCL.py
- pycqed/measurement/demonstrator_helper/execute_helpers_Starmon.py
Trying to resolve issue #415 by adding the kernel_type to the calibration data. The helper function gets the kernel_type via the json file, failing that, it reverts to a hardcoded string for that particular file, and then it sends the kernel_type together with the calibration data in a dict.
@AdriaanRol Please check this if it breaks anything. If not then, will let @quantumkoen know to close the corresponding issue in QI.
> Resolving issue #415 by adding kernel_type to send_calibration_data

- .travis.yml
- pycqed/instrument_drivers/physical_instruments/dummy_instruments.py
- pycqed/measurement/measurement_control.py
- pycqed/tests/test_MeasurementControl.py
- requirements.txt
- Example test for how to use CMA-ES optimization algorithm 
- Test that demonstrates how to use it. 
Below a mock example of how to use cma optimization. 
```python 
mock_parabola.noise(10)
MC.set_sweep_functions(
[mock_parabola.x, mock_parabola.y, mock_parabola.z])
MC.set_adaptive_function_parameters(
{'adaptive_function': cma.fmin,
'x0': [-5, 5, 5], 'sigma0': 5,  
'options':{'maxfevals': 5000,      # maximum function cals 
'cma_stds': [1, 1, 10], # Scaling for individual sigma's 
'ftarget': 0.05},        # Target function value
})
mock_parabola.noise(.5)
MC.set_detector_function(mock_parabola.parabola)
dat = MC.run('CMA test', mode='adaptive')
```
> CMA optimization test + small changes to the MC 

- pycqed/analysis/analysis_toolbox.py
Fixes No Issue
- Adds a print_pars_table function (see below)
Minor changes:
- Recovers an old function get_color_order as it was rewritten(Why? because I like to use this one, and also have a ton of code that uses this one). This old function is now called get_color_order_hsv
Example of usage
The user has been optimizing the signal of his/her qubit peak. As usual, something goes wrong, and the last 5 scans are kind of bad. So the user wants to print a table like (timestamp | RF power | Spectroscopy power) to check what were the setting in that good timestamp, 5 scans ago. So the user writes the following command:
`
print_pars_table(n_ts=10, pars={'RF.power','CW.power'})
`
And he gets the nice table with the right powers to keep his good work
About …
> Updates into analysis_toolbox

- pycqed/measurement/kernel_functions_ZI.py
@AdriaanRol: here are some small improvements of the precompensation models, which I made for my most recent simulations. The parameter ppl is now controlled via the wrapper function exponential_decay_correction_hw_friendly. There should be no change of the behavior of the functions as long as the default settings ppl = 2 and paths =8 are used.
In addition, I prevent a warning by avoiding taking the log2 of zero.
> Configurable paths, ppl; prevent log2(0)

- pycqed/measurement/openql_experiments/multi_qubit_oql.py
- pycqed/measurement/openql_experiments/pygsti_oql.py
- pycqed/measurement/openql_experiments/single_qubit_oql.py
(PR to both master and develop) Both OpenQL-0.5 and OpenQL-0.6 should work now. Fixes `set_sweep_points` interface change (no, we don't know `DeprecationWarning`)
> openql-0.6 compatibility #2

- pycqed/measurement/openql_experiments/multi_qubit_oql.py
- pycqed/measurement/openql_experiments/pygsti_oql.py
- pycqed/measurement/openql_experiments/single_qubit_oql.py
This time normal MR. Both OpenQL-0.5 and OpenQL-0.6 should work now. Fixes `set_sweep_points` interface change (no, we don't know `DeprecationWarning`)
> Openql-0.6 compatibility

- pycqed/instrument_drivers/physical_instruments/_CCL/CCLightMicrocode.py
Please use the following template for a pull request. 
When the readable control store file (see following for an example) has an empty line, the function `load_microcode` of CCL_Microcode would crash. 
```
Condition  OpTypeLeft  CW_Left  OpTypeRight  CW_Right
0:      0          0         0           0            0
1:      0          1         1           0            0
...
```
- Throw away empty lines when reading the readable control store configuration file.
@AdriaanRol
> Hotfix/ccl mc/load emptylines

- docker/Dockerfile.base
This fixes a problem of dependency resolution with pip: despite the fact that pyGSTi requires `plotly<=3.7.1`, the image appears to have later plotly. We pin the plotly version in Dockerfile explisitly. May be we will need to revert this, when pyGSTi guys will manage to update for later plotly.
> pin plotly version in Dockerfile

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_base_instrument.py
Please use the following template for a pull request. 
Partially fixes #629
- Added 'sync' method to MockServer class to enable new tests to pass that include <object>.sync() commands.
@MiguelSMoreira, @caenrigen
> Adding a 'sync' method to the MockServer class to support new tests.

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_HDAWG8.py
- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_base_instrument.py
This MR updates the HDAWG PycQED driver to check the LabOne revision in order to determine which node to write to enable the QuSurf DIO mode. The update makes the PycQED driver compatible with LabOne 20.08.
Fixes #183.
- Added LabOne version check when configuring QuSurf DIO mode in `ZI_HDAWG8`
- Improved readability of node creation in `MockDAQServer` class
- Added more nodes to `MockDAQServer` class related to DIO for both UHFQA and HDAWG8
@MiguelSMoreira 
- travis test suite passes
- follow the PEP8 style guide 
- have tests for the …
> Updated to check LabOne revision to select which nodes to write

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/UHFQuantumController.py
Fixes #188.
- Updates UHFQA driver with a try/finally statement in the DIO calibration method to change/restore settings before/after DIO calibration to avoid triggering holdoff errors.
@MiguelSMoreira
- travis test suite passes
- follow the PEP8 style guide 
- have tests for the code
- be well documented and contain comments
Tests are not mandatory as this is generally hard to make for instruments that interact with hardware.
> Added try/except to UHFQC DIO calibration.

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_HDAWG_core.py
- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_PQSC.py
- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_base_instrument.py
- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/zi_parameter_files/node_doc_PQSC.json
This PR adds the PQSC driver from ETH and improves it with proper error handling. It also adds the standard `start` and `stop` methods, which would be the preferred way of starting the PQSC. Secondly, the PR updates the `ZI_base_instrument` class to support instruments such as the PQSC that does not have an AWG.
Fixes #180.
- Added ZI PQSC driver
- Updated ZI_base_instrument to work with instruments without an AWG.
@chellings  the name of someone you want to review this pull request. 
- travis test suite passes
- follow the PEP8 style …
> Added PQSC driver from ETH

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/UHFQuantumController.py
- pycqed/tests/instrument_drivers/physical_instruments/test_UHFQC.py
Fixes #191.
- Added `minimum_holdoff` attribute to `UHFQuantumController` class.
- Added unit test of `minimum_holdoff` attribute.
- Attribute returns the minimum hold-off in units of seconds between two readout operations.
@chellings 
- test suite (Github actions) passes
- follow the PEP8 style guide 
- have tests for the code
- be well documented and contain comments
Tests are not mandatory as this is generally hard to make for instruments that interact with hardware.
> Added function to return minimum readout hold-off including unit test.

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_base_instrument.py
- pycqed/tests/instrument_drivers/physical_instruments/test_UHFQC.py
The purpose of this PR is to add support for setting device settings faster by not waiting for a response from the server. The functionality is implemented using `asyncBegin` and `asyncEnd` added to the base class of the ZI drivers. Use the functionality like this:
```
uhf = UHFQC(...)
uhf.asyncBegin()
uhf.sigouts_0_on(1)
uhf.sigouts_1_on(1)
uhf.sigouts_0_imp50(True)
uhf.sigouts_1_imp50(True)
uhf.asyncEnd()
```
The driver will wait for all the writes to complete after `asyncEnd()` is called.
Fixes #192.
- Added `asyncBegin` and `asyncEnd` methods to `ZI_base_instrument`
- Updated such that `asyncSetInt` and `asyncSetDouble` are used after `asyncBegin` 
- Updated such that `asyncEnd` calls the `daq.sync()` function causing the driver to wait for all …
> Added functionality to use asynchronous versions of the setter functions to speed up device configuration

- pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_base_instrument.py
- pycqed/tests/instrument_drivers/physical_instruments/test_UHFQA_core.py
Fixed bug in `_get_waveform_table` preventing start() from working in UHFQA_core. After refactoring there was some functionality preventing `UHFQA_core` and derived classes from executing experiments.
- Changed default implementation of `_get_waveform_table` to return an empty `dict()`
- Added unittest of `start()` for `UHFQA_core
@chellings 
- test suite (Github actions) passes
- follow the PEP8 style guide 
- have tests for the code
- be well documented and contain comments
Tests are not mandatory as this is generally hard to make for …
> Making UHFQA_core work

- requirements.txt
- setup.py
- Unpin the `plotly` and `pyGSTi` versions in `requirements.txt`
The `plotly` version is old, and the reason for pinning it (pyGSTi) is not valid any more (#542) in more recent versions.
> [WIP] remove old fix on plotly version

- deprecated/pycqed/instrument_drivers/physical_instruments/ZurichInstruments/attic/zishell.py
Avoid log message spam from `ziDAQServer` by raising the log level to
3 (status).
Completes #663.
@MiguelSMoreira
> Raise zishell's logging level to status

- .pre-commit-config.yaml
- Add pre-commit configuration file
@wvlothuizen The [pre-commit](https://pre-commit.com/) configuration add automatic formatting to all committed files using `autopep8` and `pyupgrade`. More tools can be added, see for example the config file for [qtt](https://github.com/QuTech-Delft/qtt/blob/dev/.pre-commit-config.yaml). For pycqed3 this initial configuration is quite conservative.
> add pre-commit configuration
