pycqed/init/Nader_init.py, pycqed/instrument_drivers/virtual_instruments/pyqx/qx_client.py, pycqed/measurement/detector_functions.py, pycqed/measurement/sweep_functions.py
Added QX Sweep Function
Added QX Detector Function
=> Added QX Client Interface

pycqed/measurement/hdf5_data.py, pycqed/measurement/pulse_sequences/fluxing_sequences.py
I corrected two errors incorporated in PR #54 :
- Fluxing sequences not updated for new fixed point correction funciton
- Data path forced to be within pycqed folder
=> fixing problems after merge PR54

examples/Setting up a basic measurement using the MC.ipynb, pycqed/instrument_drivers/meta_instrument/qubit_objects/qubit_object.py, pycqed/measurement/detector_functions.py, pycqed/measurement/measurement_control.py, pycqed/tests/test_MeasurementControl.py
@Nader-Khammassi Please merge this into your branch (Intel Demo) when you are ready.
=> Soft averaging

examples/Setting up a basic measurement using the MC.ipynb, pycqed/instrument_drivers/physical_instruments/dummy_instruments.py, pycqed/measurement/detector_functions.py, pycqed/measurement/measurement_control.py, pycqed/tests/test_MeasurementControl.py
@elrama- As requested in #61 I have now implemented soft averaging for soft sweeps. This works both for 1D, 2D and N-D. 
This pull request contains 
* Updated example notebook, including some options for the MC and adaptive sweeps 
* new tests for adaptive measurements as well as for soft averaging for soft sweeps. 
Check it out and let's merge it!
=> Soft averaging for soft sweeps 

examples/Setting up a basic measurement using the MC.ipynb, pycqed/measurement/hdf5_data.py, pycqed/measurement/measurement_control.py, pycqed/tests/test_MeasurementControl.py
Closes #69 
Changes in this pull request 
* replaces my custom build plot-monitor with the QCoDeS plot monitor (this was previously used only for the 2D plotting). 
* Adds a "plotting_interval" parameter to the MC that determines how often the live plot updates
Below is a screenshot of what the updated plotting looks like.
=> Prettier plotting

pycqed/instrument_drivers/physical_instruments/QuTech_ControlBoxdriver.py
Hotfix for errors introduced in v2 driver when moving to v3 driver.
=> Hotfix for CBox_v2 (taken from before _PR59 branch from Ramiro)

pycqed/analysis/tomography.py
Qutip based code for state tomography based on an arbitrary order of applied clifford gates and arbitrary number of qubits.
=> Added n qubit general linear and MLE  tomography toolbox

pycqed/instrument_drivers/physical_instruments/QuTech_ControlBox_v3.py
Discussed with @gtaifu closes #124 
@gtaifu  if you give this OK I will merge.
=> Added CBox start and stop functionality

pycqed/instrument_drivers/physical_instruments/QuTech_AWG_Module.py
- Adds a size check and range check upon uploading waveforms 
- reduces number of codewords in driver (until hardware is updated)
=> Qwg hotfixes

pycqed/measurement/waveform_control/pulse.py
@AdriaanRol Simple pulse to interpolate between two setpoints.
=> add linear pulse

pycqed/measurement/optimization.py, pycqed/tests/test_MeasurementControl.py
Implemented the SPSA algorithm for the adaptive control of MC
Implemented the tests for this algorithm
For future: After acquiring more experience, decide on optimal values for the gain parameters
=> Spsa optimization

pycqed/instrument_drivers/meta_instrument/CBox_LookuptableManager.py, pycqed/measurement/waveform_control_CC/waveform.py, pycqed/tests/test_waveforms.py
Added possibility to define an arbitrary phase for a gauss pulse.
=> Gauss Pulse Phase

pycqed/analysis/PSD/standard_arches_psd.py, pycqed/analysis/composite_analysis.py, pycqed/analysis/decoupling/decoupling_analysis.py, pycqed/analysis/fit_toolbox/functions.py, pycqed/analysis/fitting_models.py, pycqed/analysis/process_tomography.py, pycqed/analysis/tools/data_manipulation.py, pycqed/analysis/tools/plotting.py
In order to get @NielsBultink up to date with the master we first need to merge all of the Starmon branch. This is a big PR to merge all the analsysis files of that branch into the master. 
After this set of big merges no big (dirty) merges should be required anymore.
=> Analysis files from starmon branch

pycqed/instrument_drivers/meta_instrument/kernel_object.py, pycqed/measurement/kernel_functions.py, pycqed/measurement/pulse_sequences/fluxing_sequences.py, pycqed/measurement/pulse_sequences/multi_qubit_tek_seq_elts.py, pycqed/measurement/pulse_sequences/single_qubit_tek_seq_elts.py, pycqed/measurement/pulse_sequences/standard_elements.py, pycqed/measurement/waveform_control/pulse_library.py, pycqed/measurement/waveform_control/viewer.py, pycqed/measurement/waveform_control_CC/qasm_helpers.py, pycqed/measurement/waveform_control_CC/qasm_to_asm.py, pycqed/measurement/waveform_control_CC/single_qubit_qasm_seqs.py, pycqed/measurement/waveform_control_CC/waveform.py, pycqed/tests/fluxing_sequences_tests.py
Big merge similar to #206 . After these are merged, no more dirty merges required.
=> Waveform control files from starmon branch

pycqed/analysis/measurement_analysis.py
Fixed some bugs where there were non-integer indices and adjusted plot layout to fix title overlapping with subplot labels.
=> Bugfixes for standard analysis

pycqed/utilities/general.py
Convenience function. Added here so we don't have to define it in the init. 
@NielsBultink this is the snippet I showed you yesterday. If you approve you can merge it.
=> Execfile snippet from python 2

pycqed/analysis/analysis_toolbox.py, pycqed/analysis/measurement_analysis.py, pycqed/measurement/hdf5_data.py
Very small non-intrusive changes.
Added optional argument of "datadir" folder to analysis functions and hdf5 saving so loading the config file is no longer required when just using some timestamp related functions.
=> Added optional argument of "datadir" folder to analysis functions

examples/listing_instruments.py
Example on how to visualize visa resources.
=> Example Visa.resourcemanager

pycqed/analysis/measurement_analysis.py
New analysis class for data acquired with the VNA.
Data are plotted (and the image saved) in dB.
This is convinient because the VNA returns amplitue/phase and real/imag
=> VNA analysis

pycqed/utilities/general.py
Please use the following template for a pull request. 
- fixed an issue that prevented the get_git_hash function from working 
Note that to have this working git still needs to be installed on the system shell, this is separate from the github app.
=> Fixed a bug preventing the get_git_hash function from working

pycqed/measurement/measurement_control.py, pycqed/tests/test_MeasurementControl.py, requirements.txt
- Added pyqtgraph to the requirements.txt 
- fixed a but in the MC live plotting interval given upon construction of the MC
- This allows running tests on any code involving pyqtgraph
=> Pyqtgraph tests

pycqed/measurement/waveform_control/element.py
This is a start to adress #306 
@AdriaanRol @antsr
=> reduce number of function calls to sample

examples/pulse_scheme_example.py, pycqed/tests/test_pulse_scheme_drawer.py, pycqed/utilities/pulse_scheme.py
This PR contains some code I wrote to plot pulse schemes.
Features:
- Create a figure with axes and frame disabled to draw the pulse scheme on
- MW pulse (modulated Gaussian) with optional label
- Simple flux pulse (smoothed square pulse with shaded area)
- Labeling an interval with arrows, optional vertical lines and an optional text label
A simple example for the usage is included.
It should be quite straight forward to add new pulse shapes as needed.
=> Pulse Scheme Plotting

pycqed/measurement/demonstrator_helper/execute_helpers_CCL.py, pycqed/measurement/demonstrator_helper/execute_helpers_Starmon.py, pycqed/measurement/sweep_functions.py
Same as PR #384
- Added the execution helpers for CCL and Starmon
- Started a branch based on Proj/NovDemo and cherry picked files from feature/qumis_infinity_helpers
=> Added and cherrypicked certain files from feature/qumis_infinity_helpers

pycqed/instrument_drivers/physical_instruments/QuTech_AWG_Module.py, pycqed/measurement/demonstrator_helper/execute_helpers_CCL.py, pycqed/measurement/demonstrator_helper/execute_helpers_Starmon.py, pycqed/measurement/hdf5_data.py, pycqed/measurement/openql_experiments/generate_CBox_cfg.py
This is the exact commit which works for the demo of 09/11/2017 in Pokemon: Milestone V0.5
=> Resolved issue #400 by creating a generator for cbox config (Milestone V0.5 of QI)

pycqed/measurement/openql_experiments/generate_CBox_cfg.py
I just added the enumerate function for the list of qubits and used the first output to the awg field.
=> Fix for issue #407 by enumerating the list of qubits

pycqed/instrument_drivers/physical_instruments/QuTech_AWG_Module.py
Hotfix for intel demo:
Disable getSystemStatus: QWGs in demo does not support these functionalities.
=> Hotfix for intel demo: Disable get system status

pycqed/instrument_drivers/physical_instruments/Fridge_monitor.py
Update the fridge monitor to know about Bluefors fridge.  Also cleaned the fridgemon code in a few places. Tested, still works with all other fridges.
=> Update Fridge Monitor for Bluefors fridge

pycqed/analysis_v2/base_analysis.py
analysis_v2 does not delete other (old) analysis results anymore
as discussed with @AdriaanRol
=> Bugfix: make analysis non-destructive

pycqed/analysis/analysis_toolbox.py
=> bugfix: always sort the order of folder correctly

pycqed/instrument_drivers/physical_instruments/_CCL/CCLightMicrocode.py
Added a function in CCLight Microcode to read from binary
=> added a function read binary control store in CCLightMicrocode

pycqed/analysis_v2/base_analysis.py, pycqed/analysis_v2/spectroscopy_analysis.py
=> Add spectroscopy analysis from thij's branch #455

pycqed/instrument_drivers/physical_instruments/QuTech_CCL.py
This is a trivial addition w.r.t. @AdriaanRol 's request in PR #429 .
=> Added CCL driver version to CCL idn.

.gitlab-ci.yml
Need this to be merged to enable automatic rebuild of Docker images in CI
=> Fix authentication during pushing Docker image

.gitlab-ci.yml, docker/Dockerfile.base, docker/Dockerfile.testing
The problem was missing libxkbcommon-x11.so.0 library in the image, that lead to the fact that virtual display failed to initialize. Fixed in Dockerfile.
=> Fix CI builds

.codecov.yml
The content of the file is a matter of discussion, now I allowed it to reduce coverage by 5%.
=> Add codecov YAML file

.codecov.yml
=> Hotfix for codecov patch

pycqed/instrument_drivers/meta_instrument/LutMans/mw_lutman.py
This includes the QWG lutman developed and used in the VQE experiment. It will serve as the base for the development of a new QWG LutMan, compatible with the new QWGs
=> Taken from Debug/Tomo. Version last running on VQE experiment, Nov-2018

pycqed/instrument_drivers/physical_instruments/QuTech_CCL.py, pycqed/instrument_drivers/physical_instruments/QuTech_QCC.py
- changes to CCL and QCC drivers to ensure that proper assembler is being utilized; user warned otherwise. These changes reflect the modifications recently performed on UserEnv repository to install both CCL and QCC assembler separately on a system.
@AdriaanRol @jacobdesterke
=> Changes to CCL/QCC drivers for assembler compatibility

pycqed/instrument_drivers/physical_instruments/QuTech_AWG_Module.py
Workaround for #566, the proper solution needs to wait till QCodes releases https://github.com/QCoDeS/Qcodes/pull/1653.
Added: 
* A way to exclude parameters from the snapshot (workaround)
* Added QWG parameters which are not useful for the snapshot 
@AdriaanRol @elrama-
=> QWG: Added workaround for snapshot parameters exclude

pycqed/analysis/tools/plot_interpolation.py, pycqed/analysis_v2/fluxing_analysis.py, pycqed/analysis_v2/measurement_analysis.py, pycqed/measurement/waveform_control_CC/waveforms_flux.py, pycqed/simulations/cz_superoperator_simulation_new2.py, pycqed/simulations/cz_superoperator_simulation_new_functions.py
- refactored code to match CZ simulation notebook, only works for NE
- implemented circular interpolation and color scale for 'deg' units
@AdriaanRol
=> Victor dev

pycqed/analysis_v2/fluxing_analysis.py, pycqed/instrument_drivers/meta_instrument/LutMans/flux_lutman.py, pycqed/instrument_drivers/virtual_instruments/noise_parameters_CZ_new.py, pycqed/instrument_drivers/virtual_instruments/sim_control_CZ.py, pycqed/simulations/cz_superoperator_simulation_new2.py, pycqed/simulations/cz_superoperator_simulation_new_functions.py
Changes:
- improved conditional oscillation heat maps analysis
- refactored some CZ simulation
- new parameters in the fluxlutman for CZ simulations
=> CZ simulation and condition oscillation improvement

pycqed/analysis_v2/fluxing_analysis.py, pycqed/instrument_drivers/meta_instrument/LutMans/flux_lutman.py, pycqed/instrument_drivers/virtual_instruments/sim_control_CZ.py, pycqed/simulations/cz_superoperator_simulation_new2.py, pycqed/simulations/cz_superoperator_simulation_new_functions.py, pycqed/tests/instrument_drivers/meta_instrument/LutMans/test_flux_lutman.py
- Improved Conditional Oscillation Heatmaps Analysis
- Redesigned some parts of the CZ simulation
- Improved integration with fluxlutman
@MiguelSMoreira
=> final pull request from enh/QCC_integration-Victor

pycqed/analysis_v2/fluxing_analysis.py
- get it from raw values
- include it in the proc_dict_data['proc_dict_data']
- add to plot any parameter in the proc_dict_data['optimal_pnt']
Fixes #589.
=> improvement for optimal point

pycqed/instrument_drivers/virtual_instruments/sim_control_CZ.py, pycqed/simulations/cz_superoperator_simulation_new2.py, pycqed/simulations/cz_superoperator_simulation_new_functions.py
=> multi cz sim and arbitrary cost function possible

pycqed/instrument_drivers/physical_instruments/ZurichInstruments/UHFQuantumController.py, pycqed/instrument_drivers/physical_instruments/ZurichInstruments/ZI_base_instrument.py
This pull request adds two features to the ZI drivers. 
First, a new argument is introduced when creating the driver called `logfile`. If this argument is set (default is not to set it) then a text logfile will be generated where all commands sent to the device are logged. The file format is such that it can be executed in a Python notebook where the original objects are available. The goal is to assist with debugging.
Second a new acquisition mode is added which aims to resolve Git issue #146. The `acquisition` functions now take a new argument `poll` with a default value of `True`. With the default value the functionality is unchanged. If the parameter is set to `False` then the function will instead of polling for data wait for the AWG to finish and then manually read out the data. …
=> Log file creation for debugging purposes and alternative data acquisition mode

pycqed/analysis/analysis_toolbox.py
- Add missing import
@wvlothuizen
=> add missing import
